#############################################################################
# Makefile for building: pcms
# Generated by qmake (2.01a) (Qt 4.6.4) on: ?? ???? 10 15:29:58 2014
# Project:  pcms.pro
# Template: app
# Command: /usr/lib/qt46/bin/qmake -spec /usr/lib/qt46/mkspecs/linux-g++ -unix -o Makefile pcms.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib/qt46/mkspecs/linux-g++ -I. -I/usr/lib/qt46/include/QtCore -I/usr/lib/qt46/include/QtNetwork -I/usr/lib/qt46/include/QtGui -I/usr/lib/qt46/include -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/qt46/lib -lQtGui -L/usr/lib/qt46/lib -lQtNetwork -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/qt46/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = 
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		form_about.cpp \
		formoptions.cpp \
		sleeplength.cpp moc_mainwindow.cpp \
		moc_form_about.cpp \
		moc_formoptions.cpp \
		moc_sleeplength.cpp \
		qrc_pcmsRes.cpp
OBJECTS       = main.o \
		mainwindow.o \
		form_about.o \
		formoptions.o \
		sleeplength.o \
		moc_mainwindow.o \
		moc_form_about.o \
		moc_formoptions.o \
		moc_sleeplength.o \
		qrc_pcmsRes.o
DIST          = /usr/lib/qt46/mkspecs/common/g++.conf \
		/usr/lib/qt46/mkspecs/common/unix.conf \
		/usr/lib/qt46/mkspecs/common/linux.conf \
		/usr/lib/qt46/mkspecs/qconfig.pri \
		/usr/lib/qt46/mkspecs/features/qt_functions.prf \
		/usr/lib/qt46/mkspecs/features/qt_config.prf \
		/usr/lib/qt46/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt46/mkspecs/features/default_pre.prf \
		/usr/lib/qt46/mkspecs/features/release.prf \
		/usr/lib/qt46/mkspecs/features/default_post.prf \
		/usr/lib/qt46/mkspecs/features/warn_on.prf \
		/usr/lib/qt46/mkspecs/features/qt.prf \
		/usr/lib/qt46/mkspecs/features/unix/thread.prf \
		/usr/lib/qt46/mkspecs/features/moc.prf \
		/usr/lib/qt46/mkspecs/features/resources.prf \
		/usr/lib/qt46/mkspecs/features/uic.prf \
		/usr/lib/qt46/mkspecs/features/yacc.prf \
		/usr/lib/qt46/mkspecs/features/lex.prf \
		/usr/lib/qt46/mkspecs/features/include_source_dir.prf \
		pcms.pro
QMAKE_TARGET  = pcms
DESTDIR       = 
TARGET        = pcms

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): ui_mainwindow.h ui_form_about.h ui_formoptions.h ui_sleeplength.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: pcms.pro  /usr/lib/qt46/mkspecs/linux-g++/qmake.conf /usr/lib/qt46/mkspecs/common/g++.conf \
		/usr/lib/qt46/mkspecs/common/unix.conf \
		/usr/lib/qt46/mkspecs/common/linux.conf \
		/usr/lib/qt46/mkspecs/qconfig.pri \
		/usr/lib/qt46/mkspecs/features/qt_functions.prf \
		/usr/lib/qt46/mkspecs/features/qt_config.prf \
		/usr/lib/qt46/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt46/mkspecs/features/default_pre.prf \
		/usr/lib/qt46/mkspecs/features/release.prf \
		/usr/lib/qt46/mkspecs/features/default_post.prf \
		/usr/lib/qt46/mkspecs/features/warn_on.prf \
		/usr/lib/qt46/mkspecs/features/qt.prf \
		/usr/lib/qt46/mkspecs/features/unix/thread.prf \
		/usr/lib/qt46/mkspecs/features/moc.prf \
		/usr/lib/qt46/mkspecs/features/resources.prf \
		/usr/lib/qt46/mkspecs/features/uic.prf \
		/usr/lib/qt46/mkspecs/features/yacc.prf \
		/usr/lib/qt46/mkspecs/features/lex.prf \
		/usr/lib/qt46/mkspecs/features/include_source_dir.prf \
		/usr/lib/qt46/lib/libQtGui.prl \
		/usr/lib/qt46/lib/libQtCore.prl \
		/usr/lib/qt46/lib/libQtNetwork.prl
	$(QMAKE) -spec /usr/lib/qt46/mkspecs/linux-g++ -unix -o Makefile pcms.pro
/usr/lib/qt46/mkspecs/common/g++.conf:
/usr/lib/qt46/mkspecs/common/unix.conf:
/usr/lib/qt46/mkspecs/common/linux.conf:
/usr/lib/qt46/mkspecs/qconfig.pri:
/usr/lib/qt46/mkspecs/features/qt_functions.prf:
/usr/lib/qt46/mkspecs/features/qt_config.prf:
/usr/lib/qt46/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt46/mkspecs/features/default_pre.prf:
/usr/lib/qt46/mkspecs/features/release.prf:
/usr/lib/qt46/mkspecs/features/default_post.prf:
/usr/lib/qt46/mkspecs/features/warn_on.prf:
/usr/lib/qt46/mkspecs/features/qt.prf:
/usr/lib/qt46/mkspecs/features/unix/thread.prf:
/usr/lib/qt46/mkspecs/features/moc.prf:
/usr/lib/qt46/mkspecs/features/resources.prf:
/usr/lib/qt46/mkspecs/features/uic.prf:
/usr/lib/qt46/mkspecs/features/yacc.prf:
/usr/lib/qt46/mkspecs/features/lex.prf:
/usr/lib/qt46/mkspecs/features/include_source_dir.prf:
/usr/lib/qt46/lib/libQtGui.prl:
/usr/lib/qt46/lib/libQtCore.prl:
/usr/lib/qt46/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/lib/qt46/mkspecs/linux-g++ -unix -o Makefile pcms.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/pcms1.0.0 || $(MKDIR) .tmp/pcms1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/pcms1.0.0/ && $(COPY_FILE) --parents mainwindow.h form_about.h formoptions.h sleeplength.h .tmp/pcms1.0.0/ && $(COPY_FILE) --parents pcmsRes.qrc .tmp/pcms1.0.0/ && $(COPY_FILE) --parents main.cpp mainwindow.cpp form_about.cpp formoptions.cpp sleeplength.cpp .tmp/pcms1.0.0/ && $(COPY_FILE) --parents mainwindow.ui form_about.ui formoptions.ui sleeplength.ui .tmp/pcms1.0.0/ && (cd `dirname .tmp/pcms1.0.0` && $(TAR) pcms1.0.0.tar pcms1.0.0 && $(COMPRESS) pcms1.0.0.tar) && $(MOVE) `dirname .tmp/pcms1.0.0`/pcms1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/pcms1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_form_about.cpp moc_formoptions.cpp moc_sleeplength.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_form_about.cpp moc_formoptions.cpp moc_sleeplength.cpp
moc_mainwindow.cpp: mainwindow.h
	/usr/lib/qt46/bin/moc $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_form_about.cpp: form_about.h
	/usr/lib/qt46/bin/moc $(DEFINES) $(INCPATH) form_about.h -o moc_form_about.cpp

moc_formoptions.cpp: formoptions.h
	/usr/lib/qt46/bin/moc $(DEFINES) $(INCPATH) formoptions.h -o moc_formoptions.cpp

moc_sleeplength.cpp: sleeplength.h
	/usr/lib/qt46/bin/moc $(DEFINES) $(INCPATH) sleeplength.h -o moc_sleeplength.cpp

compiler_rcc_make_all: qrc_pcmsRes.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_pcmsRes.cpp
qrc_pcmsRes.cpp: pcmsRes.qrc \
		Images/factory.ico \
		Images/connect32_h.bmp \
		Images/disconnect32.bmp \
		Images/stop_48_d.bmp \
		Images/watermark_32_h.bmp \
		Images/stop24_d.bmp \
		Images/watermark_48.bmp \
		Images/stop_32.bmp \
		Images/disconnect24.bmp \
		Images/preferences32_h.bmp \
		Images/FACTORY.bmp \
		Images/preferences_48.bmp \
		Images/stop_32_d.bmp \
		Images/stop24.bmp \
		Images/niiis_logo.bmp \
		Images/stop_48_h.bmp \
		Images/connect24.bmp
	/usr/lib/qt46/bin/rcc -name pcmsRes pcmsRes.qrc -o qrc_pcmsRes.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_mainwindow.h ui_form_about.h ui_formoptions.h ui_sleeplength.h
compiler_uic_clean:
	-$(DEL_FILE) ui_mainwindow.h ui_form_about.h ui_formoptions.h ui_sleeplength.h
ui_mainwindow.h: mainwindow.ui
	/usr/lib/qt46/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_form_about.h: form_about.ui
	/usr/lib/qt46/bin/uic form_about.ui -o ui_form_about.h

ui_formoptions.h: formoptions.ui
	/usr/lib/qt46/bin/uic formoptions.ui -o ui_formoptions.h

ui_sleeplength.h: sleeplength.ui
	/usr/lib/qt46/bin/uic sleeplength.ui -o ui_sleeplength.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

main.o: main.cpp mainwindow.h \
		form_about.h \
		formoptions.h \
		sleeplength.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		ui_mainwindow.h \
		form_about.h \
		formoptions.h \
		sleeplength.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

form_about.o: form_about.cpp form_about.h \
		ui_form_about.h \
		mainwindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o form_about.o form_about.cpp

formoptions.o: formoptions.cpp formoptions.h \
		ui_formoptions.h \
		mainwindow.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o formoptions.o formoptions.cpp

sleeplength.o: sleeplength.cpp sleeplength.h \
		ui_sleeplength.h \
		mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sleeplength.o sleeplength.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_form_about.o: moc_form_about.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_form_about.o moc_form_about.cpp

moc_formoptions.o: moc_formoptions.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_formoptions.o moc_formoptions.cpp

moc_sleeplength.o: moc_sleeplength.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sleeplength.o moc_sleeplength.cpp

qrc_pcmsRes.o: qrc_pcmsRes.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_pcmsRes.o qrc_pcmsRes.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

